version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    ports:
      - 8004:8000
    environment:
      - OPEN_WEATHER_API_SECRET=f7dc8c9d6eb102c24be125e6917b4676
    depends_on:
      - db
      - rabbitmq

  db:
    restart: always
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5436:5432


  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672


  consumer-ukraine:
    build: .
    command: python app/async_cons.py 'Ukraine'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5673:5673

  consumer-uk:
    build: .
    command: python app/async_cons.py 'UK'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5674:5674

  consumer-italy:
    build: .
    command: python app/async_cons.py 'Italy'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5675:5675

  consumer-usa:
    build: .
    command: python app/async_cons.py 'USA'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5676:5676

  consumer-china:
    build: .
    command: python app/async_cons.py 'China'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5677:5677

  consumer-other:
    build: .
    command: python app/async_cons.py 'other'
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env
    ports:
      - 5678:5678


volumes:
  pgdata:
