version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/d_app
    ports:
      - 8004:8000
    environment:
      - OPEN_WEATHER_API_SECRET=f7dc8c9d6eb102c24be125e6917b4676
    networks:
      - network
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5436:5432
    networks:
      - network

  rabbit-mq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  consumer-ukraine:
    build: .
    command: python app/async_cons.py 'Ukraine'
    restart: always
    env_file: .env
    networks:
      - network
  consumer-uk:
    build: .
    command: python app/async_cons.py 'UK'
    restart: always
    env_file: .env
    networks:
      - network
  consumer-italy:
    build: .
    command: python app/async_cons.py 'Italy'
    restart: always
    env_file: .env
    networks:
      - network
  consumer-china:
    build: .
    command: python app/async_cons.py 'China'
    restart: always
    env_file: .env
    networks:
      - network
  consumer-usa:
    build: .
    command: python app/async_cons.py 'USA'
    restart: always
    env_file: .env
    networks:
      - network
  consumer-other:
    build: .
    command: python app/async_cons.py 'other'
    restart: always
    env_file: .env
    networks:
      - network

volumes:
  pgdata:

networks:
  network:
