FROM node:17-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY ./front/package.json ./
COPY ./front/yarn.lock ./
COPY ./front/src ./src
COPY ./front/public ./public

RUN yarn install
RUN yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY ./front/nginx.default.conf /etc/nginx/conf.d/default.conf
