version: "3.8"

services:
  client:
    container_name: "client"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 3000:80
    depends_on:
      - web

  web:
    container_name: "web"
    build:
      context: .
      dockerfile: Dockerfile.api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .files_data:/home/myapp/weather_project/.files_data
    ports:
      - 8004:8000
    environment:
      - OPEN_WEATHER_API_SECRET=f7dc8c9d6eb102c24be125e6917b4676
    depends_on:
      - db
      - rabbitmq

  db:
    container_name: "db"
    restart: always
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5436:5432

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  consumer-1:
    container_name: "consumer"
    build:
      context: .
      dockerfile: Dockerfile.api
    command: python app/consumer.py
    restart: always
    volumes:
      - .files_data:/home/myapp/weather_project/.files_data
    depends_on:
      - rabbitmq
      - db
      - web
    env_file: .env

volumes:
  pgdata:
