version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/d_app
    ports:
      - 8004:8000
    environment:
      - OPEN_WEATHER_API_SECRET=f7dc8c9d6eb102c24be125e6917b4676
    depends_on:
      - db
  db:
    restart: always
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - 5436:5432
volumes:
  pgdata:

