export const GET_WEATHER_URL = "http://localhost:8004/api/weather"
export const GET_STATISTIC_URL = "http://localhost:8004/api/statistic"

export const START_LOADING_WEATHER = "START_LOADING_WEATHER"
export const STOP_LOADING_WEATHER = "STOP_LOADING_WEATHER"
export const REFRESH_DATA_WEATHER = "REFRESH_DATA_WEATHER"

export const START_LOADING_STATISTIC = "START_LOADING_STATISTICs"
export const STOP_LOADING_STATISTIC = "STOP_LOADING_STATISTIC"
export const REFRESH_DATA_STATISTIC = "REFRESH_DATA_STATISTIC"
